language: r
cache: packages
r:
- bioc-release
r_packages:
- textshaping
- pheatmap
- pkgdown
# - devtools
bioc_packages:
- BSgenome.Hsapiens.UCSC.hg38
- JASPAR2018
r_github_packages:
- GreenleafLab/chromVARmotifs
- demuellae/muLogR
- demuellae/muReportR
- demuellae/muRtools
- GreenleafLab/ChrAccR
- GreenleafLab/ChrAccRex
addons:
  apt:
    packages:
#   - libgsl0ldbl
    - libgsl0-dev
# before_script:
#   - Rscript -e 'devtools::document()'
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
warnings_are_errors: false
# automatically build pkgdown site using the gh-pages branch
after_success:
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

################################################################################
# To avoid exceeding TRAVIS time limit:
# 1. Remove 'Suggests:' (except knitr) from DESCRIPTION
# 2. add 'r_build_args: --no-build-vignettes' to this file (.travis.yml)
################################################################################
